# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
prodbyrow_c <- function(mat, vec) {
    .Call(`_FNMLE_prodbyrow_c`, mat, vec)
}

#' @export
permsign_c <- function(n) {
    .Call(`_FNMLE_permsign_c`, n)
}

